name: "Run behaviour test"
description: "Run a behaviour test with common setup (Docker, Node, Playwright, ngrok)"

inputs:
  test-command:
    description: "npm test command to run (e.g., test:bundleBehaviour)"
    required: true
  artifact-prefix:
    description: "Prefix for artifact names (e.g., bundle, obligation)"
    required: true
  node-version:
    description: "Node.js version to use"
    required: true
  ngrok-auth-token:
    description: "ngrok authentication token"
    required: true
  test-hmrc-username:
    description: "HMRC test username"
    required: false
  test-hmrc-password:
    description: "HMRC test password"
    required: false
  test-hmrc-vat-number:
    description: "HMRC test VAT number"
    required: false
  hmrc-client-secret:
    description: "HMRC client secret"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: |
        npm install
        npx playwright install chromium --with-deps

    - name: Authenticate ngrok
      shell: bash
      env:
        NGROK_AUTH_TOKEN: ${{ inputs.ngrok-auth-token }}
      run: |
        npx ngrok config add-authtoken "${NGROK_AUTH_TOKEN?}"

    - name: Run behaviour test
      shell: bash
      run: |
        npm run ${{ inputs.test-command }} || exit_code=$? \
        ; cp ./target/submit*.log ./target/behaviour-test-results/ || true \
        ; exit ${exit_code:-0} \
        ;
      env:
        TEST_HMRC_USERNAME: ${{ inputs.test-hmrc-username }}
        TEST_HMRC_PASSWORD: ${{ inputs.test-hmrc-password }}
        TEST_HMRC_VAT_NUMBER: ${{ inputs.test-hmrc-vat-number }}
        HMRC_CLIENT_SECRET: ${{ inputs.hmrc-client-secret }}

    - name: Upload artifacts (results)
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v5
      with:
        name: behaviour-test-artifacts-${{ inputs.artifact-prefix }}
        retention-days: 30
        path: |
          target/behaviour-test-results/

    - name: Upload artifacts (reports)
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v5
      with:
        name: behaviour-test-reports-${{ inputs.artifact-prefix }}
        retention-days: 30
        path: |
          target/test-reports/
