# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

# Configuration variables used in workflows (from GitHub repository settings)
config-variables:
  - AWS_CERTIFICATE_ARN
  - ROOT_HOSTED_ZONE_ID
  - AWS_HOSTED_ZONE_NAME
  - COGNITO_USER_POOL_ARN
  - COGNITO_CLIENT_ID
  - GATEWAY_ACCOUNT_ID
  - GATEWAY_ACTIONS_ROLE_ARN
  - GATEWAY_DEPLOY_ROLE_ARN
  - GATEWAY_CERTIFICATE_ARN
  - SPREADSHEETS_ACCOUNT_ID
  - SPREADSHEETS_ACTIONS_ROLE_ARN
  - SPREADSHEETS_DEPLOY_ROLE_ARN
  - SPREADSHEETS_CERTIFICATE_ARN
  - SUBMIT_ACCOUNT_ID
  - SUBMIT_ACTIONS_ROLE_ARN
  - SUBMIT_DEPLOY_ROLE_ARN
  - SUBMIT_CERTIFICATE_ARN
  - SUBMIT_REGIONAL_CERTIFICATE_ARN
  - ROOT_ACCOUNT_ID
  - ROOT_ACTIONS_ROLE_ARN
  - ROOT_DEPLOY_ROLE_ARN

# Ignore patterns (regex)
# - Shellcheck informational warnings that don't affect workflow execution
# - Type mismatch false positives for quoted 'true'/'false' string values
ignore:
  - 'SC2001'
  - 'SC2002'
  - 'SC2015'
  - 'SC2016'
  - 'SC2076'
  - 'SC2086'
  - 'SC2129'
  - 'SC2155'
  - 'SC2207'
  - 'bool value cannot be assigned'
