name: "Set origins"
description: "Set the origin domain for a primary domain"
inputs:
  origin-domain:
    description: "Origin domain to point to."
    required: true
  apex-domain:
    description: "Apex domain to set alias for."
    required: true
  hosted-zone-id:
    description: "AWS Route 53 Hosted Zone ID for the apex domain."
    required: true
  cloudfront-distribution-id:
    description: "CloudFront Distribution ID to update aliases on."
    required: true

runs:
  using: "composite"
  steps:
    - name: Replace CloudFront aliases with origin-domain
      shell: bash
      env:
        SET_ORIGINS_ORIGIN_DOMAIN: ${{ inputs.origin-domain }}
        SET_ORIGINS_APEX_DOMAIN: ${{ inputs.apex-domain }}
        SET_ORIGINS_HOSTED_ZONE_ID: ${{ inputs.hosted-zone-id }}
        SET_ORIGINS_CLOUDFRONT_DISTRIBUTION_ID: ${{ inputs.cloudfront-distribution-id }}
      run: |
        set -euo pipefail

        # Skip alias replacement if a CloudFront default domain is provided, as it cannot be an alternate domain
        if [[ "${SET_ORIGINS_ORIGIN_DOMAIN?}" =~ \.cloudfront\.net$ ]]; then
          echo "origin-domain ends with .cloudfront.net; skipping CloudFront alias replacement."
          exit 0
        fi

        echo "Replacing CloudFront aliases on distribution ${SET_ORIGINS_CLOUDFRONT_DISTRIBUTION_ID?} with: ${SET_ORIGINS_ORIGIN_DOMAIN?}"

        ETAG=$(aws cloudfront get-distribution-config \
          --id "${SET_ORIGINS_CLOUDFRONT_DISTRIBUTION_ID?}" \
          --query 'ETag' \
          --output text)

        aws cloudfront get-distribution-config \
          --id "${SET_ORIGINS_CLOUDFRONT_DISTRIBUTION_ID?}" \
          --query 'DistributionConfig' \
          --output json > /tmp/cf-config.json

        jq --arg alias "${SET_ORIGINS_APEX_DOMAIN?}" '
          .Aliases = {Quantity: 1, Items: [$alias]}
        ' /tmp/cf-config.json > /tmp/cf-config.updated.json

        aws cloudfront update-distribution \
          --id "${SET_ORIGINS_CLOUDFRONT_DISTRIBUTION_ID?}" \
          --if-match "${ETAG}" \
          --distribution-config file:///tmp/cf-config.updated.json

        aws cloudfront wait distribution-deployed --id "${SET_ORIGINS_CLOUDFRONT_DISTRIBUTION_ID?}"

        echo "CloudFront aliases now:"
        aws cloudfront get-distribution --id "${SET_ORIGINS_CLOUDFRONT_DISTRIBUTION_ID?}" \
          --query 'Distribution.DistributionConfig.Aliases.Items' --output json

    - name: Alias apex domain to base domain
      shell: bash
      env:
        SET_ORIGINS_ORIGIN_DOMAIN: ${{ inputs.origin-domain }}
        SET_ORIGINS_APEX_DOMAIN: ${{ inputs.apex-domain }}
        SET_ORIGINS_HOSTED_ZONE_ID: ${{ inputs.hosted-zone-id }}
      run: |
        set -euo pipefail

        cat > /tmp/alias.json <<JSON
        {
          "Comment": "Alias apex domain to base domain",
          "Changes": [
            {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "${SET_ORIGINS_APEX_DOMAIN?}.",
                "Type": "A",
                "AliasTarget": {
                  "HostedZoneId": "${SET_ORIGINS_HOSTED_ZONE_ID?}",
                  "DNSName": "${SET_ORIGINS_ORIGIN_DOMAIN?}.",
                  "EvaluateTargetHealth": false
                }
              }
            },
            {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "${SET_ORIGINS_APEX_DOMAIN?}.",
                "Type": "AAAA",
                "AliasTarget": {
                  "HostedZoneId": "${SET_ORIGINS_HOSTED_ZONE_ID?}",
                  "DNSName": "${SET_ORIGINS_ORIGIN_DOMAIN?}.",
                  "EvaluateTargetHealth": false
                }
              }
            }
          ]
        }
        JSON

        echo "Upserting alias records: ${SET_ORIGINS_APEX_DOMAIN?} -> ${SET_ORIGINS_ORIGIN_DOMAIN?} in hosted zone ${SET_ORIGINS_HOSTED_ZONE_ID?}"
        aws route53 change-resource-record-sets --hosted-zone-id "${SET_ORIGINS_HOSTED_ZONE_ID?}" --change-batch file:///tmp/alias.json
