name: "Set origins"
description: "Set the origin domain for a primary domain"
inputs:
  origin-domain:
    description: "Origin domain to point to."
    required: true
  apex-domain:
    description: "Apex domain to set alias for."
    required: true
  hosted-zone-id:
    description: "AWS Route 53 Hosted Zone ID for the apex domain."
    required: true

runs:
  using: "composite"
  steps:
    - name: Alias apex domain to base domain
      shell: bash
      env:
        SET_ORIGINS_ORIGIN_DOMAIN: ${{ inputs.origin-domain }}
        SET_ORIGINS_APEX_DOMAIN: ${{ inputs.apex-domain }}
        SET_ORIGINS_HOSTED_ZONE_ID: ${{ inputs.hosted-zone-id }}
      run: |
        set -euo pipefail

        cat > /tmp/alias.json <<JSON
        {
          "Comment": "Alias apex domain to base domain",
          "Changes": [
            {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "${SET_ORIGINS_APEX_DOMAIN?}.",
                "Type": "A",
                "AliasTarget": {
                  "HostedZoneId": "${SET_ORIGINS_HOSTED_ZONE_ID?}",
                  "DNSName": "${SET_ORIGINS_ORIGIN_DOMAIN?}.",
                  "EvaluateTargetHealth": false
                }
              }
            },
            {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "${SET_ORIGINS_APEX_DOMAIN?}.",
                "Type": "AAAA",
                "AliasTarget": {
                  "HostedZoneId": "${SET_ORIGINS_HOSTED_ZONE_ID?}",
                  "DNSName": "${SET_ORIGINS_ORIGIN_DOMAIN?}.",
                  "EvaluateTargetHealth": false
                }
              }
            }
          ]
        }
        JSON

        echo "Upserting alias records: ${SET_ORIGINS_APEX_DOMAIN?} -> ${SET_ORIGINS_ORIGIN_DOMAIN?} in hosted zone ${SET_ORIGINS_HOSTED_ZONE_ID?}"
        aws route53 change-resource-record-sets --hosted-zone-id "${SET_ORIGINS_HOSTED_ZONE_ID?}" --change-batch file:///tmp/alias.json
