name: "Set origins"
description: "Set the origin domain for a primary domain"
inputs:
  deploymentName:
    description: "Explicit deployment name (e.g. ci or custom). Leave empty to derive from branch."
    required: false
    default: ""
  prodBranchName:
    description: "Branch name that maps to prod."
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Alias apex domain to base domain
      shell: bash
      run: |
        set -euo pipefail

        if [ -z "${DIY_SUBMIT_APEX_DOMAIN:-}" ] || [ -z "${DIY_SUBMIT_BASE_DOMAIN:-}" ] || [ -z "${AWS_HOSTED_ZONE_ID:-}" ]; then
          echo "Required env vars DIY_SUBMIT_APEX_DOMAIN, DIY_SUBMIT_BASE_DOMAIN, and AWS_HOSTED_ZONE_ID must be set."
          exit 1
        fi

        cat > /tmp/alias.json <<JSON
        {
          "Comment": "Alias apex domain to base domain",
          "Changes": [
            {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "${DIY_SUBMIT_APEX_DOMAIN}.",
                "Type": "A",
                "AliasTarget": {
                  "HostedZoneId": "${AWS_HOSTED_ZONE_ID}",
                  "DNSName": "${DIY_SUBMIT_BASE_DOMAIN}.",
                  "EvaluateTargetHealth": false
                }
              }
            },
            {
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "${DIY_SUBMIT_APEX_DOMAIN}.",
                "Type": "AAAA",
                "AliasTarget": {
                  "HostedZoneId": "${AWS_HOSTED_ZONE_ID}",
                  "DNSName": "${DIY_SUBMIT_BASE_DOMAIN}.",
                  "EvaluateTargetHealth": false
                }
              }
            }
          ]
        }
        JSON

        echo "Upserting alias records: ${DIY_SUBMIT_APEX_DOMAIN} -> ${DIY_SUBMIT_BASE_DOMAIN} in hosted zone ${AWS_HOSTED_ZONE_ID}"
        aws route53 change-resource-record-sets --hosted-zone-id "$AWS_HOSTED_ZONE_ID" --change-batch file:///tmp/alias.json
