version = "1.1.0"

[[bundles]]
id = "default"
name = "Default"
allocation = "automatic"
auth = "none"

[[bundles]]
id = "test"
name = "Test"
allocation = "on-request"
auth = "required"
cap = 10
timeout = "P1D"

[[bundles]]
id = "guest"
name = "Guest"
allocation = "on-request"
auth = "required"
cap = 10
timeout = "P1M"

[[bundles]]
id = "legacy"
name = "Legacy"
allocation = "on-request"
auth = "required"
cap = 1000
timeout = "P1Y"
[bundles.qualifiers]
requiresTransactionId = true

[[bundles]]
id = "basic"
name = "Basic"
allocation = "on-request"
auth = "required"
[bundles.qualifiers]
subscriptionTier = "Basic"

[[bundles]]
id = "advanced"
name = "Advanced"
allocation = "on-request"
auth = "required"
[bundles.qualifiers]
subscriptionTier = "Advanced"

# Demo/placeholder activities
[[activities]]
id = "learn-free-anon"
name = "Learn about free anonymous activities"
kind = "demo"
bundles = ["default"]

[[activities]]
id = "learn-free-auth"
name = "Learn about free authenticated activities"
kind = "demo"
bundles = ["guest"]

[[activities]]
id = "learn-basic"
name = "Learn about basic activities"
kind = "demo"
bundles = ["basic"]

[[activities]]
id = "learn-legacy"
name = "Learn about DIY legacy entitlements"
kind = "demo"
bundles = ["legacy"]

[[activities]]
id = "learn-advanced"
name = "Learn about advanced activities"
kind = "demo"
bundles = ["advanced"]

# Actual activities (flat, no variants)
[[activities]]
id = "submit-vat-sandbox"
name = "Submit VAT (Sandbox API)"
kind = "actual"
bundles = ["test"]
# tags = ["sandbox"]

[[activities]]
id = "vat-obligations-sandbox"
name = "VAT Obligations (Sandbox API)"
kind = "actual"
bundles = ["test"]
# tags = ["sandbox"]

[[activities]]
id = "submit-vat"
name = "Submit VAT"
kind = "actual"
bundles = ["guest", "basic", "legacy"]

[[activities]]
id = "vat-obligations"
name = "VAT Obligations"
kind = "actual"
bundles = ["default"]

[[activities]]
id = "self-employed"
name = "Self Employed"
kind = "actual"
bundles = ["basic", "legacy"]

[[activities]]
id = "diy-basic-sole-trader-upload"
name = "DIY Basic Sole Trader Upload"
kind = "actual"
bundles = ["legacy"]

[[activities]]
id = "diy-taxi-upload"
name = "DIY Taxi Upload"
kind = "actual"
bundles = ["legacy"]

[[activities]]
id = "diy-self-employed-upload"
name = "DIY Self-Employed Upload"
kind = "actual"
bundles = ["legacy"]

[[activities]]
id = "diy-limited-company-upload"
name = "DIY Limited Company Upload"
kind = "actual"
bundles = ["legacy"]
