name: "Scale Lambda Concurrency (Alias-based)"
description: "Activate Lambda capacity tiers (zero | ready | hot) using aliases"

inputs:
  deployment-name:
    description: "Deployment name prefix (e.g. prod-abc123 or ci-refresh)"
    required: true

  concurrency-level:
    description: "Capacity tier alias to activate: zero | ready | hot"
    required: true
    default: "zero"

  aws-region:
    description: "AWS region"
    required: false
    default: "eu-west-2"

runs:
  using: "composite"

  steps:
    - name: Validate concurrency level
      shell: bash
      run: |
        LEVEL="${{ inputs.concurrency-level }}"
        if [[ "$LEVEL" != "zero" && "$LEVEL" != "ready" && "$LEVEL" != "hot" ]]; then
          echo "Invalid concurrency level: $LEVEL" >&2
          exit 1
        fi
        echo "Scaling Lambdas to '$LEVEL' capacity tier"

    - name: Discover Lambda functions
      shell: bash
      env:
        DEPLOYMENT_NAME: ${{ inputs.deployment-name }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        set -euo pipefail

        echo "Discovering Lambda functions with prefix: ${DEPLOYMENT_NAME}"

        aws lambda list-functions \
          --region "${AWS_REGION}" \
          --query "Functions[?starts_with(FunctionName, \`${DEPLOYMENT_NAME}\`)].FunctionName" \
          --output text \
          > functions.txt

        if [ ! -s functions.txt ]; then
          echo "No Lambda functions found for deployment ${DEPLOYMENT_NAME}"
          exit 0
        fi

        echo "Found $(wc -w < functions.txt) Lambda functions:"
        cat functions.txt

    - name: Activate alias tier
      shell: bash
      env:
        CONCURRENCY_LEVEL: ${{ inputs.concurrency-level }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        set -euo pipefail

        SUCCESS=0
        SKIPPED=0
        FAILED=0

        while read -r FUNCTION_NAME; do
          echo ""
          echo "Processing ${FUNCTION_NAME}"

          if ! aws lambda get-alias \
            --function-name "${FUNCTION_NAME}" \
            --name "${CONCURRENCY_LEVEL}" \
            --region "${AWS_REGION}" >/dev/null 2>&1; then
            echo "  ⚠️ Alias '${CONCURRENCY_LEVEL}' not found, skipping"
            SKIPPED=$((SKIPPED + 1))
            continue
          fi

          echo "  ✓ Alias '${CONCURRENCY_LEVEL}' exists"
          SUCCESS=$((SUCCESS + 1))
        done < functions.txt

        echo ""
        echo "========================================"
        echo "Alias Activation Summary"
        echo "========================================"
        echo "Activated: ${SUCCESS}"
        echo "Skipped:   ${SKIPPED}"
        echo "Failed:    ${FAILED}"
        echo "========================================"

        if [ "${FAILED}" -gt 0 ]; then
          exit 1
        fi

    - name: Poll provisioned concurrency readiness
      shell: bash
      env:
        CONCURRENCY_LEVEL: ${{ inputs.concurrency-level }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        set -euo pipefail

        if [ "${CONCURRENCY_LEVEL}" = "zero" ]; then
          echo "Zero tier selected; no readiness polling required"
          exit 0
        fi

        MAX_WAIT=300
        INTERVAL=10
        ELAPSED=0

        echo ""
        echo "Polling provisioned concurrency readiness..."

        while [ $ELAPSED -lt $MAX_WAIT ]; do
          NOT_READY=0

          while read -r FUNCTION_NAME; do
            STATUS=$(aws lambda get-provisioned-concurrency-config \
              --function-name "${FUNCTION_NAME}" \
              --qualifier "${CONCURRENCY_LEVEL}" \
              --region "${AWS_REGION}" \
              --query 'Status' \
              --output text 2>/dev/null || echo "NOT_CONFIGURED")

            if [ "${STATUS}" != "READY" ]; then
              NOT_READY=$((NOT_READY + 1))
            fi
          done < functions.txt

          if [ "$NOT_READY" -eq 0 ]; then
            echo "✓ All Lambdas are READY"
            exit 0
          fi

          echo "Waiting for ${NOT_READY} Lambda(s) to be ready (${ELAPSED}s elapsed)"
          sleep $INTERVAL
          ELAPSED=$((ELAPSED + INTERVAL))
        done

        echo "⚠️ Timed out waiting for provisioned concurrency readiness"
        exit 1
