name: destroy
run-name: "destroy ${{ github.event_name == 'delete' && github.event.ref || github.ref_name }}"
concurrency:
  group: deploy-${{ github.event_name == 'delete' && github.event.ref || github.ref_name }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      deploymentName:
        description: 'The name of the deployment to destroy (omit for branch-based deployments, "ci" for CI environment, "prod" for production)'
        required: false
        default: ''
  delete:

permissions:
  id-token: write
  contents: read

env:
  JAVA_VERSION: '21'
  NODE_VERSION: '22'
  ACTIONS_ROLE_ARN: 'arn:aws:iam::887764105431:role/submit-github-actions-role'
  DEPLOY_ROLE_ARN:  'arn:aws:iam::887764105431:role/submit-deployment-role'
  AWS_REGION: 'eu-west-2'
  AWS_ACCOUNT_ID: '887764105431'
  BASE_IMAGE_TAG_PREFIX: 'submit-base'
  skipDeploy: ${{ inputs.skipDeploy || 'false' }}
  deploymentName: ${{ inputs.deploymentName || '' }}
  loadTestDuration: ${{ inputs.loadTestDuration || '30s' }}
  GITHUB_ACTOR: ${{ github.actor }}
  SELF_DESTRUCT_DELAY_HOURS: ${{ inputs.selfDestructDelayHours || '1' }}
  BASE_IMAGE_TAG: ${{ github.sha }}
  FORCE_ALL_STACK_DEPLOYMENT: ${{ inputs.forceAllStackDeployment || 'false' }}
  COMMIT_HASH: ${{ github.sha }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  destroy:
    if: ${{ github.event_name != 'delete' || github.event.ref_type == 'branch' }} # skip non-branch deletions
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'delete' && github.event.ref == 'refs/heads/main') || (github.event_name != 'delete' && github.ref == 'refs/heads/main') && 'prod' || 'ci' }}
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.repository.default_branch }} # e.g. main
          fetch-depth: 0

      - name: Report deleted ref
        run: |
          echo "Deleted: ${{ github.event.ref }}"
          echo "Ref type: ${{ github.event.ref_type }}"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Compute deployment name and environment
        id: names
        run: |
          # For delete events, use the deleted ref; otherwise use current ref
          if [ "${{ github.event_name }}" = "delete" ]; then
              # Extract branch name from refs/heads/branch-name
              REF_NAME=$(echo "${{ github.event.ref }}" | sed 's|^refs/heads/||')
              echo "Delete event detected, using deleted ref: $REF_NAME"
          else
              REF_NAME="${{ github.ref_name }}"
              echo "Workflow dispatch event, using current ref: $REF_NAME"
          fi

          INPUT_DEPLOYMENT_NAME="${{ inputs.deploymentName }}"

          # Clean branch name: lowercase, replace non-alphanumeric with hyphens, collapse consecutive hyphens
          CLEANED=$(echo "$REF_NAME" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]/-/g' -e 's/-\{2,\}/-/g' -e 's/^-//' -e 's/-$//')

          if [ "$REF_NAME" = "main" ]; then
              ENVIRONMENT_NAME="prod"
              DEPLOYMENT_NAME="prod"
          elif [ "$INPUT_DEPLOYMENT_NAME" = "ci" ]; then
              ENVIRONMENT_NAME="ci"
              DEPLOYMENT_NAME="ci"
          elif [ -n "$INPUT_DEPLOYMENT_NAME" ]; then
              ENVIRONMENT_NAME="ci"
              DEPLOYMENT_NAME="$INPUT_DEPLOYMENT_NAME"
          else
              ENVIRONMENT_NAME="ci"
              # Truncate to 16 chars for branch-based deployments
              DEPLOYMENT_NAME="ci-${CLEANED:0:8}"
          fi

          echo "Computed ENVIRONMENT_NAME: $ENVIRONMENT_NAME"
          echo "Computed DEPLOYMENT_NAME: $DEPLOYMENT_NAME"
          #DEPLOYMENT_NAME=$ENVIRONMENT_NAME

          echo "ENVIRONMENT_NAME=$environmentment-name" >> "$GITHUB_OUTPUT"
          echo "DEPLOYMENT_NAME=$deployment-name" >> "$GITHUB_OUTPUT"

          echo "Actual ENVIRONMENT_NAME: $ENVIRONMENT_NAME"
          echo "Actual DEPLOYMENT_NAME: $DEPLOYMENT_NAME"

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Configure AWS role via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: false
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: Assume AWS deployment role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: CDK stacks before
        run: |
          aws cloudformation describe-stacks --region eu-west-2 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort
          aws cloudformation describe-stacks --region us-east-1 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort

      - name: Node dependencies
        run: npm ci

      - name: Build CDK
        run: ./mvnw --errors clean package -DskipTests

      - name: Destroy PublishStack
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-delivery && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              del-${{ steps.names.outputs.deployment-name }}-PublishStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          WEBSITE_HASH: 'placeholder'

      - name: Destroy EdgeStack
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-delivery && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              del-${{ steps.names.outputs.deployment-name }}-EdgeStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          WEBSITE_HASH: 'placeholder'

      - name: Destroy OpsStack
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ steps.names.outputs.deployment-name }}-OpsStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy AccountStack
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ steps.names.outputs.deployment-name }}-AccountStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy HmrcStack
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ steps.names.outputs.deployment-name }}-HmrcStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy AuthStack
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ steps.names.outputs.deployment-name }}-AuthStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy DevStack
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ steps.names.outputs.deployment-name }}-DevStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy SelfDestructStack (Delivery)
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-delivery && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              del-${{ steps.names.outputs.deployment-name }}-SelfDestructStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../${{ needs.mvn-package.outputs.self-destruct-handler-source }}"
          WEBSITE_HASH: "placeholder"

      - name: Destroy SelfDestructStack (Application)
        if: ${{ steps.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ steps.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ steps.names.outputs.deployment-name }}-SelfDestructStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../${{ needs.mvn-package.outputs.self-destruct-handler-source }}"
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: CDK stacks after
        if: ${{ !cancelled() }}
        run: |
          aws cloudformation describe-stacks --region eu-west-2 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort
          aws cloudformation describe-stacks --region us-east-1 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort
