name: destroy
run-name: "destroy ${{ github.event_name == 'delete' && github.event.ref || github.ref_name }}"
concurrency:
  group: deploy-${{ github.event_name == 'delete' && github.event.ref || github.ref_name }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: 'The name of the environment to destroy (omit for branch-based environment name or, "ci" for CI environment, "prod" for production)'
        required: false
        default: ''
      deployment-name:
        description: 'The name of the deployment to destroy (omit for branch-based deployment name or, "ci-lambdas4" for CI environment, "prod-44f0305" for production)'
        required: false
        default: ''

permissions:
  id-token: write
  contents: read

env:
  JAVA_VERSION: '21'
  NODE_VERSION: '22'
  ACTIONS_ROLE_ARN: 'arn:aws:iam::887764105431:role/submit-github-actions-role'
  DEPLOY_ROLE_ARN:  'arn:aws:iam::887764105431:role/submit-deployment-role'
  AWS_REGION: 'eu-west-2'
  AWS_ACCOUNT_ID: '887764105431'
  BASE_IMAGE_TAG_PREFIX: 'submit-base'
  GITHUB_ACTOR: ${{ github.actor }}
  SELF_DESTRUCT_DELAY_HOURS: ${{ inputs.selfDestructDelayHours || '1' }}
  BASE_IMAGE_TAG: ${{ github.sha }}
  FORCE_ALL_STACK_DEPLOYMENT: ${{ inputs.forceAllStackDeployment || 'false' }}
  COMMIT_HASH: ${{ github.sha }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  names:
    runs-on: ubuntu-24.04
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'ci' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Compute deployment name and environment
        id: deployment-config
        uses: ./.github/actions/get-names
        with:
          environment-name: ${{ inputs.environment-name }}
          deployment-name: ${{ inputs.deployment-name }}
    outputs:
      environment-name: ${{ inputs.environment-name || steps.deployment-config.outputs.environment-name }}
      deployment-name: ${{ inputs.deployment-name || steps.deployment-config.outputs.deployment-name }}
      base-domain: ${{ steps.deployment-config.outputs.base-domain }}
      base-url: ${{ steps.deployment-config.outputs.base-url }}
      apex-domain: ${{ steps.deployment-config.outputs.apex-domain }}
      apex-url: ${{ steps.deployment-config.outputs.apex-url }}
      holding-domain: ${{ steps.deployment-config.outputs.holding-domain }}
      holding-url: ${{ steps.deployment-config.outputs.holding-url }}

  destroy:
    needs:
      - names
    if: ${{ github.event_name != 'delete' || github.event.ref_type == 'branch' }} # skip non-branch deletions
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'delete' && github.event.ref == 'refs/heads/main') || (github.event_name != 'delete' && github.ref == 'refs/heads/main') && 'prod' || 'ci' }}
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.repository.default_branch }} # e.g. main
          fetch-depth: 0

      - name: Report deleted ref
        run: |
          echo "Deleted: ${{ github.event.ref }}"
          echo "Ref type: ${{ github.event.ref_type }}"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Configure AWS role via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: false
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: Assume AWS deployment role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - name: CDK stacks before
        run: |
          aws cloudformation describe-stacks --region eu-west-2 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort
          aws cloudformation describe-stacks --region us-east-1 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort

      - name: Node dependencies
        run: npm ci

      - name: Build CDK
        run: ./mvnw --errors clean package -DskipTests

      - name: Destroy PublishStack
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-delivery && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              del-${{ needs.names.outputs.deployment-name }}-PublishStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          WEBSITE_HASH: 'placeholder'

      - name: Destroy EdgeStack
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-delivery && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              del-${{ needs.names.outputs.deployment-name }}-EdgeStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          WEBSITE_HASH: 'placeholder'

      - name: Destroy OpsStack
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ needs.names.outputs.deployment-name }}-OpsStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy AccountStack
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ needs.names.outputs.deployment-name }}-AccountStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy HmrcStack
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ needs.names.outputs.deployment-name }}-HmrcStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy AuthStack
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ needs.names.outputs.deployment-name }}-AuthStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy DevStack
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ needs.names.outputs.deployment-name }}-DevStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../infra/test/resources/fake-self-destruct-lambda.jar"
          BASE_IMAGE_TAG: ${{ needs.push-images.outputs.base-image-tag }}
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: Destroy SelfDestructStack (Delivery)
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-delivery && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              del-${{ needs.names.outputs.deployment-name }}-SelfDestructStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../${{ needs.mvn-package.outputs.self-destruct-handler-source }}"
          WEBSITE_HASH: "placeholder"

      - name: Destroy SelfDestructStack (Application)
        if: ${{ needs.names.outputs.deployment-name != 'prod' }}
        run: |
          cd cdk-application && \
            npx dotenv -e ../.env.${{ needs.names.outputs.environment-name }} -- \
              npx cdk destroy \
              app-${{ needs.names.outputs.deployment-name }}-SelfDestructStack \
              --exclusively --force \
          && cd .. \
          ;
        env:
          ENVIRONMENT_NAME: ${{ needs.names.outputs.environment-name }}
          DEPLOYMENT_NAME: ${{ needs.names.outputs.deployment-name }}
          SELF_DESTRUCT_HANDLER_SOURCE: "../${{ needs.mvn-package.outputs.self-destruct-handler-source }}"
          # Set by deploy-environment.yml after the environment's AuthStack is deployed
          COGNITO_USER_POOL_ARN: ${{ vars.COGNITO_USER_POOL_ARN }}
          COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}

      - name: CDK stacks after
        if: ${{ !cancelled() }}
        run: |
          aws cloudformation describe-stacks --region eu-west-2 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort
          aws cloudformation describe-stacks --region us-east-1 --query "Stacks[].StackName" --output text | tr '\t' '\n' | sort
