# .github/workflows/formating.yml

name: formating
concurrency: write
run-name: "formating [${{ github.ref_name }}]"

on:
  workflow_dispatch:
  schedule:
    - cron: '14 4 * * *'

jobs:
  formatting:
    permissions:
      contents: write
      packages: write
      id-token: write
    #uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-npm-run-script-and-commit-to-branch.yml@6.10.2'
    uses: 'antonycc/submit.diyaccounting.co.uk/.github/workflows/wfr-npm-run-script-and-commit-to-branch.yml@main'
    with:
      script: 'npm run formatting-fix -- ${{ needs.extract-paths.outputs.allPaths }} ; npm run linting-fix ${{ needs.extract-paths.outputs.allPaths }}'
      sarifScript: ''
      testScript: 'npm run test:app-unit'
      branch: 'formatting'
      gitUserEmail: 'action@github.com'
      gitUserName: 'GitHub Actions[bot]'
      gitCommitMessage: 'npm run formatting-fix -- ${{ needs.extract-paths.outputs.allPaths }} ; npm run linting-fix ${{ needs.extract-paths.outputs.allPaths }}'

  create-pr:
    needs:
      - formatting
    if: needs.formatting.outputs.updatedFiles == 'true'
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      checks: write
      id-token: write
    uses: 'xn-intenton-z2a/agentic-lib/.github/workflows/wfr-github-create-pr.yml@6.10.2'
    with:
      branch: 'formatting'
      baseBranch: 'main'
      gitCommitMessage: 'chore: formatting fixes'
      label: 'automerge'
