# .github/workflows/test-behaviour.yml

name: test-behaviour
concurrency: ngrok
run-name: 'test behaviour [${{ github.ref_name }}] [${{ github.event.head_commit.message }}]'

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '**/*.json'
      - 'public/**'
      - 'tests/behaviour/**'
      - '.github/workflows/test-behaviour.yml'
  workflow_dispatch:
  schedule:
    - cron: '34 2,3,4 * * *'

jobs:

  npm-behaviour-test:
    name: 'npm behaviour test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci || npm install

      - name: Authenticate ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          npx ngrok config add-authtoken "${NGROK_AUTH_TOKEN?}"

      - run: npx playwright install --with-deps

      - run: npm run test:behaviour
        env:
          HMRC_BASE_URI: ${{ vars.HMRC_BASE_URI }}
          HMRC_REDIRECT_URI: ${{ vars.HMRC_REDIRECT_URI }}
          HMRC_CLIENT_ID: ${{ secrets.HMRC_CLIENT_ID }}
          HMRC_CLIENT_SECRET: ${{ secrets.HMRC_CLIENT_SECRET }}
          PORT: ${{ vars.PORT }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-behaviour
          path: behaviour-test-results/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-behaviour
          path: test-reports/
          retention-days: 30
