# .github/workflows/test-behaviour.yml

name: test-behaviour
concurrency: ngrok
run-name: "test behaviour [${{ inputs.environment || 'proxy' }}] [${{ github.ref_name }}] [${{ github.event.head_commit.message }}]"

on:
  push:
    branches:
      - main
    paths:
      - 'behaviour-tests/**'
      - 'web/public/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/test-behaviour.yml'
      - '!infra/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'proxy'
        type: choice
        options:
          - proxy
          - ci
          - prod
  schedule:
    - cron: '34 2,3,4 * * *'

env:
  environment: ${{ inputs.environment || 'proxy' }}

jobs:

  npm-behaviour-test:
    name: 'npm behaviour test'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'proxy' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci || npm install

      - name: Authenticate ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          npx ngrok config add-authtoken "${NGROK_AUTH_TOKEN?}"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - run: npx playwright install chromium --with-deps

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::887764105431:role/submit-github-actions-role
          role-chaining: false
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - run: aws sts get-caller-identity --region eu-west-2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::887764105431:role/submit-deployment-role
          role-chaining: true
          aws-region: eu-west-2
          audience: sts.amazonaws.com
          role-skip-session-tagging: true
          output-credentials: true
          retry-max-attempts: 3

      - run: aws sts get-caller-identity --region eu-west-2

      #- run: |
      #    echo "DIY_SUBMIT_HMRC_CLIENT_SECRET=${{ secrets.HMRC_CLIENT_SECRET }}" >> .env

      #- run: npm run test:behaviour
      - run: npx dotenv -e '.env.${{ env.environment }}' -- npm run test:behaviour
        if: env.environment == 'proxy'
        env:
          DIY_SUBMIT_HMRC_CLIENT_SECRET: ${{ secrets.HMRC_CLIENT_SECRET }}
      - run: cp '.env.${{ env.environment }}' '.env.proxy' ; npx dotenv -e '.env.${{ env.environment }}' -- npm run test:behaviour
        if: env.environment != 'proxy'
        env:
          DIY_SUBMIT_HMRC_CLIENT_SECRET: ${{ secrets.HMRC_CLIENT_SECRET }}

      #- run: rm -rf .env

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-behaviour
          path: target/behaviour-test-results/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: target/test-results/
          retention-days: 30

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-behaviour
          path: target/test-reports/
          retention-days: 30

      - name: Copy test server logs
        run: |
          mkdir -p test-server-logs/
          cp -r submit-*.log test-server-logs/

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-server-logs-behaviour
          path: test-server-logs/
          retention-days: 30