# .github/workflows/test-infra.yml

name: test-infra
run-name: 'test infra [${{ github.ref_name }}] [${{ github.event.head_commit.message }}]'

on:
  push:
    branches:
      - main
    paths:
      - 'aws/**'
      - '.m2/**'
      - 'mvnw'
      - '.mvn'
      - '.github/workflows/test-infra.yml'
  workflow_dispatch:
  schedule:
    - cron: '34 2,3,4 * * *'

jobs:
  mvn-test:
    name: 'maven test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'maven'

      - name: package
        id: package
        shell: bash
        run: ./mvnw clean test

  mvn-package-cdk-synth-no-env:
    name: 'cdk synth from maven package without any environment variables'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'maven'

      - name: check
        id: check
        run: cat ~/.m2/settings.xml
        if: steps.mvn.outputs.pomXmlExists == 'true'

      - name: package
        id: package
        if: steps.mvn.outputs.pomXmlExists == 'true'
        shell: bash
        run: ./mvnw clean package -DskipTests

      - name: synth
        id: synth
        if: steps.mvn.outputs.pomXmlExists == 'true'
        shell: bash
        run: npx cdk synth --strict --validation --no-staging --trace

  mvn-package-cdk-synth:
    name: 'cdk synth from maven package'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'maven'

      - name: check
        id: check
        run: cat ~/.m2/settings.xml
        if: steps.mvn.outputs.pomXmlExists == 'true'

      #- name: download-dependencies
      #  id: download-dependencies
      #  if: steps.mvn.outputs.pomXmlExists == 'true'
      #  shell: bash
      #  run: ./mvnw --batch-mode --quiet dependency:go-offline > /dev/null 2>&1

      - name: package
        id: package
        if: steps.mvn.outputs.pomXmlExists == 'true'
        shell: bash
        run: ./mvnw clean package
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          ENV_NAME: ${{ inputs.environment || 'ci' }}
          USE_EXISTING_HOSTED_ZONE: ${{ vars.USE_EXISTING_HOSTED_ZONE || 'true' }}
          USE_EXISTING_CERTIFICATE: ${{ vars.USE_EXISTING_CERTIFICATE || 'true' }}
          CLOUD_TRAIL_ENABLED: ${{ vars.AWS_CLOUD_TRAIL_ENABLED || 'false' }}
          HOSTED_ZONE_NAME: ${{ vars.AWS_HOSTED_ZONE_NAME }}
          HOSTED_ZONE_ID: ${{ vars.AWS_HOSTED_ZONE_ID }}
          CERTIFICATE_ARN: ${{ vars.AWS_CERTIFICATE_ARN }}
          SUB_DOMAIN_NAME: ${{ vars.SUB_DOMAIN_NAME || 'submit' }}
          LOG_S3_OBJECT_EVENT_HANDLER_SOURCE: ${{ steps.jar-path.outputs.jarFilepath }}
          LOG_GZIPPED_S3_OBJECT_EVENT_HANDLER_SOURCE: ${{ steps.jar-path.outputs.jarFilepath }}
          AUTH_URL_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.AUTH_URL_LAMBDA_HANDLER_FUNCTION_NAME }}
          AUTH_URL_LAMBDA_DURATION: ${{ vars.AUTH_URL_LAMBDA_DURATION }}
          EXCHANGE_TOKEN_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.EXCHANGE_TOKEN_LAMBDA_HANDLER_FUNCTION_NAME }}
          EXCHANGE_TOKEN_LAMBDA_DURATION: ${{ vars.EXCHANGE_TOKEN_LAMBDA_DURATION }}
          SUBMIT_VAT_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.SUBMIT_VAT_LAMBDA_HANDLER_FUNCTION_NAME }}
          SUBMIT_VAT_LAMBDA_DURATION: ${{ vars.SUBMIT_VAT_LAMBDA_DURATION }}
          LOG_RECEIPT_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.LOG_RECEIPT_LAMBDA_HANDLER_FUNCTION_NAME }}
          LOG_RECEIPT_LAMBDA_DURATION: ${{ vars.LOG_RECEIPT_LAMBDA_DURATION }}

      - name: synth
        id: synth
        if: steps.mvn.outputs.pomXmlExists == 'true'
        shell: bash
        run: npx cdk synth --strict --validation --no-staging --trace
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          ENV_NAME: ${{ inputs.environment || 'ci' }}
          USE_EXISTING_HOSTED_ZONE: ${{ vars.USE_EXISTING_HOSTED_ZONE || 'true' }}
          USE_EXISTING_CERTIFICATE: ${{ vars.USE_EXISTING_CERTIFICATE || 'true' }}
          CLOUD_TRAIL_ENABLED: ${{ vars.AWS_CLOUD_TRAIL_ENABLED || 'false' }}
          HOSTED_ZONE_NAME: ${{ vars.AWS_HOSTED_ZONE_NAME }}
          HOSTED_ZONE_ID: ${{ vars.AWS_HOSTED_ZONE_ID }}
          CERTIFICATE_ARN: ${{ vars.AWS_CERTIFICATE_ARN }}
          SUB_DOMAIN_NAME: ${{ vars.SUB_DOMAIN_NAME || 'submit' }}
          LOG_S3_OBJECT_EVENT_HANDLER_SOURCE: ${{ steps.jar-path.outputs.jarFilepath }}
          LOG_GZIPPED_S3_OBJECT_EVENT_HANDLER_SOURCE: ${{ steps.jar-path.outputs.jarFilepath }}
          AUTH_URL_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.AUTH_URL_LAMBDA_HANDLER_FUNCTION_NAME }}
          AUTH_URL_LAMBDA_DURATION: ${{ vars.AUTH_URL_LAMBDA_DURATION }}
          EXCHANGE_TOKEN_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.EXCHANGE_TOKEN_LAMBDA_HANDLER_FUNCTION_NAME }}
          EXCHANGE_TOKEN_LAMBDA_DURATION: ${{ vars.EXCHANGE_TOKEN_LAMBDA_DURATION }}
          SUBMIT_VAT_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.SUBMIT_VAT_LAMBDA_HANDLER_FUNCTION_NAME }}
          SUBMIT_VAT_LAMBDA_DURATION: ${{ vars.SUBMIT_VAT_LAMBDA_DURATION }}
          LOG_RECEIPT_LAMBDA_HANDLER_FUNCTION_NAME: ${{ vars.LOG_RECEIPT_LAMBDA_HANDLER_FUNCTION_NAME }}
          LOG_RECEIPT_LAMBDA_DURATION: ${{ vars.LOG_RECEIPT_LAMBDA_DURATION }}
