# .github/workflows/test-services.yml

name: test-services
run-name: 'test services [${{ github.ref_name }}] [${{ github.event.head_commit.message }}]'

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '**/*.json'
      - '.github/workflows/test-services.yml'
      - '!aws/**'
  workflow_dispatch:
  schedule:
    - cron: '34 2,3,4 * * *'

jobs:
  npm-test:
    name: 'npm test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm test
        env:
          HMRC_CLIENT_ID: ${{ secrets.HMRC_CLIENT_ID }}
          HMRC_REDIRECT_URI: ${{ vars.HMRC_REDIRECT_URI }}
          HMRC_CLIENT_SECRET: ${{ secrets.HMRC_CLIENT_SECRET }}
          HMRC_BASE_URI: ${{ vars.HMRC_BASE_URI }}
          PORT: ${{ vars.PORT }}
          TEST_REDIRECT_URI: ${{ vars.TEST_REDIRECT_URI }}
          TEST_ACCESS_TOKEN: ${{ secrets.TEST_ACCESS_TOKEN }}
          TEST_RECEIPT: ${{ vars.TEST_RECEIPT }}

  npm-build:
    name: 'npm build'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci || npm install

      - run: npm run build

  npm-unit-test:
    name: 'npm unit test with coverage'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci || npm install

      - run: npm run test:coverage
        env:
          HMRC_CLIENT_ID: ${{ secrets.HMRC_CLIENT_ID }}
          HMRC_REDIRECT_URI: ${{ vars.HMRC_REDIRECT_URI }}
          HMRC_CLIENT_SECRET: ${{ secrets.HMRC_CLIENT_SECRET }}
          HMRC_BASE_URI: ${{ vars.HMRC_BASE_URI }}
          PORT: ${{ vars.PORT }}
          TEST_REDIRECT_URI: ${{ vars.TEST_REDIRECT_URI }}
          TEST_ACCESS_TOKEN: ${{ secrets.TEST_ACCESS_TOKEN }}
          TEST_RECEIPT: ${{ vars.TEST_RECEIPT }}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports-services
          path: coverage/
          retention-days: 30

  npm-integration-test:
    name: 'npm integration test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci || npm install

      - run: npm run test:integration

  npm-system-test:
    name: 'npm system test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci || npm install

      - run: npm run test:system